[package]
name = "actix_navigation_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-service = "2.0.2"
actix-web = "4.3.1"
scraper = "0.15.0"
zip = "0.6.4"
