version: "3.9"

services:
  mongo:
    container_name: ${DB_CONTAINER_NAME}
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
  navigation:
    container_name: ${NAVIGATION_CONTAINER_NAME}
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - NAVIGATION_CONTAINER_NAME=${NAVIGATION_CONTAINER_NAME}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
