version: "3.9"

services:
  mongo:
    container_name: ${DB_CONTAINER_NAME}
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
        #  navigation:
        #    container_name: ${NAVIGATION_CONTAINER_NAME}
        #    build: .
        #    ports:
        #      - 8084:8080
        #    environment:
        #      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
        #      - NAVIGATION_CONTAINER_NAME=${NAVIGATION_CONTAINER_NAME}
        #      - MONGODB_USERNAME=${MONGODB_USERNAME}
        #      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
